# Generated by Django 5.2.6 on 2025-09-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
