# Generated by Django 5.2.6 on 2025-09-29 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_maintenancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rental_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('electricity_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('electricity_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('water_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('water_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('previous_water_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_water_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.rentalcontract')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
