# Generated by Django 5.2.6 on 2025-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='electricity_meter_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_meter_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
