# Generated by Django 5.2.6 on 2025-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_unit_electricity_meter_reading_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('property', 'unit_number'), name='unique_unit_number_per_property'),
        ),
    ]
