# Generated by Django 5.2.6 on 2025-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_unit_unique_unit_number_per_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='current_electricity_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='previous_electricity_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
