# Generated by Django 5.2.6 on 2025-11-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_receipt_current_electricity_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_water_bill', models.BooleanField(default=True)),
                ('has_electricity_bill', models.BooleanField(default=True)),
                ('has_service_charge', models.BooleanField(default=True)),
                ('has_security_charge', models.BooleanField(default=False)),
                ('has_other_charges', models.BooleanField(default=False)),
                ('rent_deposit_months', models.PositiveIntegerField(default=1)),
                ('require_water_deposit', models.BooleanField(default=False)),
                ('require_electricity_deposit', models.BooleanField(default=False)),
                ('allow_partial_payments', models.BooleanField(default=True)),
                ('auto_generate_receipts', models.BooleanField(default=False)),
                ('late_payment_penalty_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage penalty for late rent (e.g., 2.5 means 2.5%)', max_digits=5)),
                ('grace_period_days', models.PositiveIntegerField(default=5)),
                ('default_service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_security_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_other_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_parameters', to='app.property')),
            ],
        ),
    ]
