# Generated by Django 5.2.6 on 2025-11-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_systemparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='customer',
        ),
    ]
