# Generated by Django 5.2.6 on 2025-11-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_maintenancerequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app.customer'),
        ),
    ]
