# Generated by Django 5.2.6 on 2025-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_maintenancerequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemparameter',
            name='electicity_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='water_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
