# Generated by Django 5.2.6 on 2025-11-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_systemparameter_electicity_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=10),
        ),
    ]
