# Generated by Django 5.2.6 on 2025-11-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_receipt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='contract',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.receipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
