# Generated by Django 5.2.6 on 2025-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_payment_contract_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
