# Generated by Django 5.2.6 on 2025-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_receipt_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
