# Generated by Django 5.2.6 on 2025-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_receipt_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='unit',
            name='total_billed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='unit',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
