# Generated by Django 5.2.6 on 2025-11-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_unit_balance_unit_total_billed_unit_total_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemparameter',
            name='electricity_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='water_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
