# Generated by Django 5.2.6 on 2025-11-24 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_payment_type_alter_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.expense'),
        ),
        migrations.AddField(
            model_name='payment',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.maintenancerequest'),
        ),
    ]
