# Generated by Django 5.2.6 on 2025-11-24 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_payment_expense_payment_maintenance_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='app.property'),
        ),
    ]
