# Generated by Django 5.2.6 on 2025-11-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_payment_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='property',
        ),
    ]
